apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName | default "my-cluster-secrets"}} # needs to be the same as PerconaXtraDBCluster.spec.secretsName
type: Opaque
stringData:
  root: root_password
  xtrabackup: backup_password
  monitor: monitory
  clustercheck: clustercheckpassword
  proxyadmin: admin_password
  pmmserver: admin
  operator: operatoradmin
